"""add moodle_id to programs.

Revision ID: 0573f34c6171
Revises: 2be461fc64c6
Create Date: 2024-09-14 04:50:01.855785

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0573f34c6171"
down_revision: Union[str, None] = "2be461fc64c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("program", sa.Column("moodle_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("program", "moodle_id")
    # ### end Alembic commands ###
