"""add moodle_id to program semesters.

Revision ID: 2be461fc64c6
Revises: b8d8eafb9ab7
Create Date: 2024-09-14 04:29:26.874780

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2be461fc64c6"
down_revision: Union[str, None] = "b8d8eafb9ab7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "program_semester", sa.Column("moodle_id", sa.Integer(), nullable=True)
    )
    op.drop_column("program_semester", "id_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "program_semester",
        sa.Column("id_number", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("program_semester", "moodle_id")
    # ### end Alembic commands ###
