"""add moodle_id to file.

Revision ID: 34f955788fab
Revises: c13ca07a0ca0
Create Date: 2025-01-02 11:16:40.423915

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34f955788fab"
down_revision: Union[str, None] = "c13ca07a0ca0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("moodle_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "moodle_id")
    # ### end Alembic commands ###
