"""add moodle_id to material.

Revision ID: c13ca07a0ca0
Revises: f81419ddfd91
Create Date: 2025-01-02 08:48:40.484660

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c13ca07a0ca0"
down_revision: Union[str, None] = "f81419ddfd91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("material", sa.Column("moodle_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("material", "moodle_id")
    # ### end Alembic commands ###
