"""add moodle_id to course.

Revision ID: f81419ddfd91
Revises: 0573f34c6171
Create Date: 2024-09-14 05:24:06.971529

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f81419ddfd91"
down_revision: Union[str, None] = "0573f34c6171"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("moodle_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "moodle_id")
    # ### end Alembic commands ###
